# all numbers in picobarns

# to do: cross-section values for H+c and H+b samples are nowhere
# clearly and unambiguously written down.
# in fact there are contradicting numbers all over the place.
# need to figure this out.

# signal sample
# cross-section from https://github.com/colizz/UFHZZAnalysisRun2/blob/UL_10_6_26_HiggsCharm/Utilities/crab/SampleList_UL18_signal_BKG_HiggsCharm_r2_main.txt
0.00009013 HPlusCharm_4FS_MuRFScaleDynX0p50_HToZZTo4L_M125_TuneCP5_13TeV_amcatnloFXFX_JHUGenV7011_pythia8

# background H+b
# cross-section from AN-2023-094
# (cross-section in the AN is given for HtoGG, but this seems to be a mistake,
# as the value for the H+c (HtoGG) sample corresponds to the one above)
0.0006654 HPlusBottom_5FS_MuRFScaleDynX0p50_HToZZTo4L_M125_TuneCP5_13TeV_amcatnloFXFX_JHUGenV7011_pythia8

# background regular H production
# cross-section from https://github.com/H-charm/NanoHc/blob/b4b6fd6e1bee309c1f58ec6f3d8d1088e6224e69/run/samples/xsec.conf#L24
0.01334 GluGluHToZZTo4L_M125_TuneCP5_13TeV_powheg2_JHUGenV7011_pythia8
0.001038 VBF_HToZZTo4L_M125_TuneCP5_13TeV_powheg2_JHUGenV7011_pythia8

# other backgrounds (to be extended later, but qqZZ is by far the dominant background)
# cross-section from https://github.com/H-charm/NanoHc/blob/b4b6fd6e1bee309c1f58ec6f3d8d1088e6224e69/run/samples/xsec.conf#L45
1.256 ZZTo4L_TuneCP5_13TeV_powheg_pythia8
